services:
  postgres:
    image: postgres:16-alpine
    container_name: mappening-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "55432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/scripts/postgres-dev-init.sql:/docker-entrypoint-initdb.d/001-init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

    # Cache pour optimiser les performances API
  redis:
    image: redis:7-alpine
    container_name: mappening-redis
    ports:
      - "6379:6379" # Port redis exposé sur l'hôte
        # Persistance des données redis, Mode AOF (persistance fiable), Redémarrage automatique sauf arrêt manuel
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
