BEGIN;

INSERT INTO accounts (
    id,
    account_type_id,
    login_email,
    password_hash,
    is_active,
    created_at,
    updated_at
) VALUES
    (10, 3, 'culture@example.fr', '$2a$10$OF8SaEuOlrf4eFy365SA.eN5jCZ1lkje/NljP9rT5WMabYJq9pV4q', TRUE, '2026-05-19 08:00:00', '2026-05-19 08:00:00'),
    (11, 3, 'food@example.fr', '$2a$10$OF8SaEuOlrf4eFy365SA.eN5jCZ1lkje/NljP9rT5WMabYJq9pV4q', TRUE, '2026-05-19 09:00:00', '2026-05-19 09:00:00'),
    (12, 3, 'pending-organization@example.fr', '$2a$10$OF8SaEuOlrf4eFy365SA.eN5jCZ1lkje/NljP9rT5WMabYJq9pV4q', TRUE, '2026-05-28 11:00:00', '2026-05-28 11:00:00'),
    (13, 3, 'sport@example.fr', '$2a$10$OF8SaEuOlrf4eFy365SA.eN5jCZ1lkje/NljP9rT5WMabYJq9pV4q', TRUE, '2026-05-22 16:30:00', '2026-05-22 16:30:00')
ON CONFLICT (id) DO UPDATE
SET
    account_type_id = EXCLUDED.account_type_id,
    login_email = EXCLUDED.login_email,
    password_hash = EXCLUDED.password_hash,
    is_active = EXCLUDED.is_active,
    deleted_at = NULL,
    updated_at = EXCLUDED.updated_at;

SELECT setval(
    pg_get_serial_sequence('accounts', 'id'),
    GREATEST((SELECT MAX(id) FROM accounts), 1),
    (SELECT COUNT(*) > 0 FROM accounts)
);

INSERT INTO organizations (
    id,
    account_id,
    name,
    contact_email,
    role_id,
    description,
    website,
    latitude,
    longitude,
    address,
    city,
    postal_code,
    logo,
    contact_phone_number,
    siret,
    is_verified,
    is_active,
    created_at,
    updated_at
) VALUES
    (
        101,
        10,
        'Éclat Culture',
        'contact@eclat-culture.fr',
        3,
        'Collectif marseillais qui organise concerts, expositions et rencontres culturelles.',
        'https://eclat-culture.fr',
        43.296500,
        5.369800,
        '12 rue de la République',
        'Marseille',
        '13002',
        'https://images.unsplash.com/photo-1517457373958-b7bdd4587205',
        '0611223344',
        '12345678901234',
        TRUE,
        TRUE,
        '2026-05-19 08:00:00',
        '2026-05-25 12:00:00'
    ),
    (
        102,
        11,
        'Food Lab Provence',
        'hello@foodlab-provence.fr',
        3,
        'Organisateur de marchés gourmands, ateliers cuisine et rendez-vous food en Provence.',
        'https://foodlab-provence.fr',
        43.529700,
        5.447400,
        '5 cours Mirabeau',
        'Aix-en-Provence',
        '13100',
        'https://images.unsplash.com/photo-1504674900247-0877df9cc836',
        '0622334455',
        '23456789012345',
        TRUE,
        TRUE,
        '2026-05-19 09:00:00',
        '2026-05-26 13:30:00'
    ),
    (
        103,
        12,
        'Atelier Horizon',
        'contact@atelier-horizon.fr',
        3,
        'Jeune structure en attente de validation, spécialisée dans les ateliers créatifs.',
        'https://atelier-horizon.fr',
        43.344200,
        5.407500,
        '44 boulevard Baille',
        'Marseille',
        '13005',
        'https://images.unsplash.com/photo-1519389950473-47ba0277781c',
        '0633445566',
        '34567890123456',
        FALSE,
        FALSE,
        '2026-05-28 11:00:00',
        '2026-05-28 11:00:00'
    ),
    (
        104,
        13,
        'Outdoor Sud',
        'contact@outdoor-sud.fr',
        3,
        'Association sportive locale dédiée aux sorties nature et événements plein air.',
        'https://outdoor-sud.fr',
        43.214000,
        5.539000,
        '2 avenue des Calanques',
        'Cassis',
        '13260',
        'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee',
        '0644556677',
        '45678901234567',
        TRUE,
        TRUE,
        '2026-05-22 16:30:00',
        '2026-05-27 09:15:00'
    )
ON CONFLICT (id) DO UPDATE
SET
    account_id = EXCLUDED.account_id,
    name = EXCLUDED.name,
    contact_email = EXCLUDED.contact_email,
    role_id = EXCLUDED.role_id,
    description = EXCLUDED.description,
    website = EXCLUDED.website,
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude,
    address = EXCLUDED.address,
    city = EXCLUDED.city,
    postal_code = EXCLUDED.postal_code,
    logo = EXCLUDED.logo,
    contact_phone_number = EXCLUDED.contact_phone_number,
    siret = EXCLUDED.siret,
    is_verified = EXCLUDED.is_verified,
    is_active = EXCLUDED.is_active,
    deleted_at = NULL,
    updated_at = EXCLUDED.updated_at;

SELECT setval(
    pg_get_serial_sequence('organizations', 'id'),
    GREATEST((SELECT MAX(id) FROM organizations), 1),
    (SELECT COUNT(*) > 0 FROM organizations)
);

INSERT INTO event_categories (id, name, slug) VALUES
    (1, 'animaux', 'animaux'),
    (2, 'art', 'art'),
    (3, 'associatif', 'associatif'),
    (4, 'atelier', 'atelier'),
    (5, 'automobile', 'automobile'),
    (6, 'bien-etre', 'bien-etre'),
    (7, 'business', 'business'),
    (8, 'cinema', 'cinema'),
    (9, 'concert', 'concert'),
    (10, 'conference', 'conference'),
    (11, 'culture', 'culture'),
    (12, 'emploi', 'emploi'),
    (13, 'enfants', 'enfants'),
    (14, 'esport', 'esport'),
    (15, 'famille', 'famille'),
    (16, 'festival', 'festival'),
    (17, 'food', 'food'),
    (18, 'formation', 'formation'),
    (19, 'gaming', 'gaming'),
    (20, 'gastronomie', 'gastronomie'),
    (21, 'humour', 'humour'),
    (22, 'jeux', 'jeux'),
    (23, 'marche', 'marche'),
    (24, 'mode', 'mode'),
    (25, 'musique', 'musique'),
    (26, 'nature', 'nature'),
    (27, 'networking', 'networking'),
    (28, 'nightlife', 'nightlife'),
    (29, 'patrimoine', 'patrimoine'),
    (30, 'plein-air', 'plein-air'),
    (31, 'randonnee', 'randonnee'),
    (32, 'sante', 'sante'),
    (33, 'shopping', 'shopping'),
    (34, 'solidarite', 'solidarite'),
    (35, 'soiree', 'soiree'),
    (36, 'spectacle', 'spectacle'),
    (37, 'sport', 'sport'),
    (38, 'technologie', 'technologie'),
    (39, 'theatre', 'theatre'),
    (40, 'tourisme', 'tourisme'),
    (41, 'etudiant', 'etudiant'),
    (42, 'exposition', 'exposition')
ON CONFLICT (id) DO UPDATE
SET
    name = EXCLUDED.name,
    slug = EXCLUDED.slug,
    updated_at = NOW();

SELECT setval(
    pg_get_serial_sequence('event_categories', 'id'),
    GREATEST((SELECT MAX(id) FROM event_categories), 1),
    (SELECT COUNT(*) > 0 FROM event_categories)
);

WITH seeded_events (
    id,
    organization_id,
    title,
    description,
    start_date,
    end_date,
    latitude,
    longitude,
    address,
    city,
    postal_code,
    image,
    price,
    ticketing_link,
    source,
    is_active,
    created_at,
    updated_at,
    deleted_at
) AS (
    VALUES
        (
            1001::BIGINT,
            101::BIGINT,
            'Jazz sur le Vieux-Port',
            'Concert en plein air aujourd''hui avec trois formations jazz locales et vue sur le Vieux-Port.',
            CURRENT_DATE + TIME '08:00:00',
            CURRENT_DATE + TIME '23:59:00',
            43.296500::DECIMAL(9,6),
            5.369800::DECIMAL(9,6),
            'Quai du Port',
            'Marseille',
            '13002',
            'https://images.unsplash.com/photo-1511379938547-c1f69419868d',
            18.00::DECIMAL(10,2),
            'https://billetterie.eclat-culture.fr/jazz-vieux-port',
            'eclat-culture.fr',
            TRUE,
            '2026-05-21 09:00:00'::TIMESTAMP,
            '2026-05-21 09:00:00'::TIMESTAMP,
            NULL::TIMESTAMP
        ),
        (
            1002,
            102,
            'Marché gourmand de Provence',
            'Food trucks, producteurs locaux, dégustations et animations culinaires demain toute la journée.',
            CURRENT_DATE + INTERVAL '1 day' + TIME '09:00:00',
            CURRENT_DATE + INTERVAL '1 day' + TIME '18:00:00',
            43.529700,
            5.447400,
            'Cours Mirabeau',
            'Aix-en-Provence',
            '13100',
            'https://images.unsplash.com/photo-1555939594-58d7cb561ad1',
            0.00,
            '',
            'foodlab-provence.fr',
            TRUE,
            '2026-05-22 10:15:00',
            '2026-05-23 08:00:00',
            NULL
        ),
        (
            1003,
            104,
            'Randonnée crépusculaire dans les Calanques',
            'Sortie accompagnée au coucher du soleil, niveau facile, départ depuis Cassis.',
            CURRENT_DATE + INTERVAL '3 days' + TIME '16:00:00',
            CURRENT_DATE + INTERVAL '3 days' + TIME '20:30:00',
            43.214000,
            5.539000,
            'Port de Cassis',
            'Cassis',
            '13260',
            'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee',
            12.50,
            'outdoor-sud.fr/billetterie/calanques-crepuscule',
            'outdoor-sud.fr',
            TRUE,
            '2026-05-24 16:30:00',
            '2026-05-24 16:30:00',
            NULL
        ),
        (
            1004,
            101,
            'Expo photo: Marseille de nuit',
            'Exposition immersive dédiée aux paysages urbains et aux ports illuminés.',
            CURRENT_DATE + INTERVAL '4 days' + TIME '17:00:00',
            CURRENT_DATE + INTERVAL '4 days' + TIME '21:00:00',
            43.300700,
            5.380600,
            '41 rue Jobin',
            'Marseille',
            '13003',
            'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429',
            6.00,
            '',
            'eclat-culture.fr',
            FALSE,
            '2026-05-29 14:00:00',
            '2026-05-29 14:00:00',
            NULL
        ),
        (
            1005,
            102,
            'Atelier cuisine méditerranéenne',
            'Session passée pour tester l''affichage de l''historique et des événements terminés.',
            CURRENT_DATE - INTERVAL '7 days' + TIME '13:00:00',
            CURRENT_DATE - INTERVAL '7 days' + TIME '16:00:00',
            43.526300,
            5.445400,
            '18 rue des Cordeliers',
            'Aix-en-Provence',
            '13100',
            'https://images.unsplash.com/photo-1556911220-bff31c812dba',
            35.00,
            'https://foodlab-provence.fr/ateliers/cuisine-mediterraneenne',
            'foodlab-provence.fr',
            TRUE,
            '2026-05-10 12:00:00',
            '2026-05-10 12:00:00',
            NULL
        ),
        (
            1006,
            103,
            'Atelier design solidaire',
            'Événement proposé par une organisation encore en attente de validation administrateur.',
            CURRENT_DATE + INTERVAL '2 days' + TIME '08:00:00',
            CURRENT_DATE + INTERVAL '2 days' + TIME '11:30:00',
            43.344200,
            5.407500,
            '44 boulevard Baille',
            'Marseille',
            '13005',
            'https://images.unsplash.com/photo-1519389950473-47ba0277781c',
            0.00,
            '',
            'atelier-horizon.fr',
            FALSE,
            '2026-05-30 11:00:00',
            '2026-05-30 11:00:00',
            NULL
        ),
        (
            1007,
            101,
            'Conférence web et accessibilité',
            'Rencontre technique sans coordonnées GPS pour vérifier l''affichage liste sans marker carte.',
            CURRENT_DATE + INTERVAL '5 days' + TIME '15:00:00',
            CURRENT_DATE + INTERVAL '5 days' + TIME '17:00:00',
            NULL,
            NULL,
            'La Coque, Place Henri Verneuil',
            'Marseille',
            '13002',
            'https://images.unsplash.com/photo-1521737604893-d14cc237f11d',
            0.00,
            'https://eclat-culture.fr/conference-accessibilite',
            'eclat-culture.fr',
            TRUE,
            '2026-05-31 10:30:00',
            '2026-05-31 10:30:00',
            NULL
        ),
        (
            1008,
            104,
            'Course annulée du bord de mer',
            'Événement soft-deleted pour vérifier qu''il ne ressort ni dans la liste ni dans la carte.',
            CURRENT_DATE + INTERVAL '7 days' + TIME '07:00:00',
            CURRENT_DATE + INTERVAL '7 days' + TIME '10:00:00',
            43.174900,
            5.604400,
            'Plage de la Ciotat',
            'La Ciotat',
            '13600',
            'https://images.unsplash.com/photo-1461896836934-ffe607ba8211',
            10.00,
            '',
            'outdoor-sud.fr',
            FALSE,
            '2026-05-26 09:00:00',
            '2026-06-01 09:00:00',
            '2026-06-01 09:00:00'
        )
)
INSERT INTO events (
    id,
    organization_id,
    title,
    description,
    start_date,
    end_date,
    latitude,
    longitude,
    address,
    city,
    postal_code,
    image,
    price,
    ticketing_link,
    source,
    is_active,
    created_at,
    updated_at,
    deleted_at
)
SELECT
    id,
    organization_id,
    title,
    description,
    start_date,
    end_date,
    latitude,
    longitude,
    address,
    city,
    postal_code,
    image,
    price,
    ticketing_link,
    source,
    is_active,
    created_at,
    updated_at,
    deleted_at
FROM seeded_events
ON CONFLICT (id) DO UPDATE
SET
    organization_id = EXCLUDED.organization_id,
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    start_date = EXCLUDED.start_date,
    end_date = EXCLUDED.end_date,
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude,
    address = EXCLUDED.address,
    city = EXCLUDED.city,
    postal_code = EXCLUDED.postal_code,
    image = EXCLUDED.image,
    price = EXCLUDED.price,
    ticketing_link = EXCLUDED.ticketing_link,
    source = EXCLUDED.source,
    is_active = EXCLUDED.is_active,
    updated_at = EXCLUDED.updated_at,
    deleted_at = EXCLUDED.deleted_at;

SELECT setval(
    pg_get_serial_sequence('events', 'id'),
    GREATEST((SELECT MAX(id) FROM events), 1),
    (SELECT COUNT(*) > 0 FROM events)
);

DELETE FROM event_categories_links
WHERE event_id BETWEEN 1001 AND 1008;

WITH event_category_links(event_id, category_slug) AS (
    VALUES
        (1001::BIGINT, 'musique'),
        (1001, 'concert'),
        (1001, 'culture'),
        (1002, 'gastronomie'),
        (1002, 'food'),
        (1002, 'festival'),
        (1003, 'sport'),
        (1003, 'nature'),
        (1003, 'randonnee'),
        (1003, 'plein-air'),
        (1004, 'exposition'),
        (1004, 'art'),
        (1004, 'culture'),
        (1005, 'atelier'),
        (1005, 'gastronomie'),
        (1005, 'formation'),
        (1006, 'atelier'),
        (1006, 'solidarite'),
        (1006, 'art'),
        (1007, 'conference'),
        (1007, 'technologie'),
        (1007, 'formation'),
        (1008, 'sport'),
        (1008, 'plein-air')
)
INSERT INTO event_categories_links (event_id, event_category_id)
SELECT event_category_links.event_id, event_categories.id
FROM event_category_links
JOIN event_categories ON event_categories.slug = event_category_links.category_slug
ON CONFLICT (event_id, event_category_id) DO NOTHING;

SELECT setval(
    pg_get_serial_sequence('event_categories_links', 'id'),
    GREATEST((SELECT MAX(id) FROM event_categories_links), 1),
    (SELECT COUNT(*) > 0 FROM event_categories_links)
);

COMMIT;
