/**Centralisation des routes de l'application */

export const ROUTES = {
  PUBLIC: {
    HOME: "/",
    LOGIN: "/login",
    FORGOT_PASSWORD: "/forgot-password",
    RESET_PASSWORD: "/reset-password/:token",
    REGISTER: "/register",
  },

  USER: {
    ACCOUNT: "/account",
    PROFILE: "/account/profile",
    FAVORITES: "/account/favorites",
    HISTORY: "/account/history",
    NOTIFICATIONS: "/account/notifications",
    CHANGE_PASSWORD: "/account/profile/change-password",
    ONBOARDING: "/onboarding",
    PARAMETERS: "/account/parameters",
    ORGANIZATIONS: "/account/organizations",
    EVENTS: "/account/events",
    ORGANIZATION_DETAIL: "/account/organizations/:organizationId",
    BECOME_ORGANIZER: "/account/organizations/devenir-organisateur",
    CREATE_ORGANIZATION: "/account/organizations/new",
  },

  LEGACY_USER: {
    PROFILE: "/profile",
    FAVORITES: "/favorites",
    HISTORY: "/history",
    NOTIFICATIONS: "/notifications",
    CHANGE_PASSWORD: "/profile/change-password",
    PREFERENCES: "/preferences",
    ORGANIZATIONS: "/organizations",
    EVENTS: "/my-events",
    ORGANIZATION_DETAIL: "/organizations/:organizationId",
    BECOME_ORGANIZER: "/organizations/devenir-organisateur",
    CREATE_ORGANIZATION: "/organizations/new",
  },

  ADMIN: {
    DASHBOARD: "/administration",
    EVENTS: "/administration/events",
    PROFILE: "/administration/profile",
    PARAMETERS: "/administration/parameters",
    USERS: "/administration",
  },
  LEGACY_ADMIN: {
    DASHBOARD: "/admin",
    EVENTS: "/admin/events",
    PROFILE: "/admin/profile",
    PREFERENCES: "/admin/preferences",
    USERS: "/admin/users",
  },
  MODERATOR: {
    DASHBOARD: "/moderation",
    EVENTS: "/moderation/events",
    ORGANIZATIONS: "/moderation/organizations",
    ACCOUNTS: "/moderation/accounts",
    REPORTS: "/moderation/reports",
    PROFILE: "/moderation/profile",
    PARAMETERS: "/moderation/parameters",
  },
  LEGACY_MODERATOR: {
    DASHBOARD: "/moderator",
    EVENTS: "/moderator/events",
    ORGANIZATIONS: "/moderator/organizations",
    ACCOUNTS: "/moderator/accounts",
    REPORTS: "/moderator/reports",
    PROFILE: "/moderator/profile",
    PREFERENCES: "/moderator/preferences",
  },
  ORGANIZATION: {
    DASHBOARD: "/organization",
    EVENTS: "/organization/events",
    CREATE: "/organization/create",
    PROFILE: "/organization/profile",
  },
} as const;
